# Origin: Generated by Gemini (Google DeepMind)
# https://github.com/squillero/computer-sciences
# Free under certain conditions — see the license for details.


def load_report(filename):
    """
    Reads the report file and separates dangerous ranges from purchased batches.
    """
    ranges = []
    batches = []
    reading_ranges = True

    try:
        with open(filename, 'r') as f:
            for line in f:
                line = line.strip()

                # If we hit an empty line, switch mode from reading ranges to reading batches
                if not line:
                    if reading_ranges:
                        reading_ranges = False
                    continue

                if reading_ranges:
                    # Parse range string "min-max" into integers
                    try:
                        start, end = map(int, line.split('-'))
                        ranges.append((start, end))
                    except ValueError:
                        print(f"Warning: Could not parse range '{line}'")
                else:
                    # Parse batch number into integer
                    try:
                        batches.append(int(line))
                    except ValueError:
                        print(f"Warning: Could not parse batch number '{line}'")

    except FileNotFoundError:
        print(f"Error: The file '{filename}' was not found.")
        return [], []

    return ranges, batches


def is_dangerous(batch_num, dangerous_ranges):
    """
    Returns True if the batch_num falls into any of the dangerous_ranges.
    """
    for start, end in dangerous_ranges:
        if start <= batch_num <= end:
            return True
    return False


def main():
    filename = 'report-small.txt'
    dangerous_ranges, purchased_batches = load_report(filename)

    # If file reading failed, exit
    if not dangerous_ranges and not purchased_batches:
        return

    # Check each batch
    for batch in purchased_batches:
        if is_dangerous(batch, dangerous_ranges):
            print(batch)


if __name__ == "__main__":
    main()
