print("Hello world!")
print("Hello")
print("My")
print("Full", "name", "is")
print()
print("is")
print("Giovanni Adolfo Pio Pietro")
print("And", "my", "favorite", "number", "is", 42)

print("Hello, I'm Johnny")
print('Hello, I am Johnny')
print("""Hello, I'm Johnny and I say "hi!".""")
print('''Hello''')
